In [4]:
from pprint import pprint
import pandas as pd
from omegaconf import OmegaConf
from embedding_train.config import load_base_config
from embedding_train.data import EmbeddingDataModule
cfg = load_base_config()
cfg = OmegaConf.merge(
    cfg,
    {
        "data": {
            "num_workers": 0,
            "pin_memory": False,
            "limit_rows": 10000,
        }
    },
)
dm = EmbeddingDataModule(cfg)
dm.setup()
print("dataset stats:")
pprint(dm.dataset_stats)
print("\ntrain sample (raw records):")
display(pd.DataFrame(dm.train_dataset.records).head(5))
print("\nval sample (raw records):")
display(pd.DataFrame(dm.val_dataset.records).head(5))
train_batch = next(iter(dm.train_dataloader()))
val_batch = next(iter(dm.val_dataloader()))
def preview_batch(batch):
    return pd.DataFrame({
        "query_id": batch["query_ids"],
        "offer_id": batch["offer_ids"],
        "label": batch["labels"].tolist(),
        "raw_label": batch["raw_labels"],
        "query_text": [
            dm.tokenizer.decode(ids, skip_special_tokens=True)
            for ids in batch["query_inputs"]["input_ids"]
        ],
        "offer_text": [
            dm.tokenizer.decode(ids, skip_special_tokens=True)
            for ids in batch["offer_inputs"]["input_ids"]
        ],
        "query_tokens": [
            int(mask.sum()) for mask in batch["query_inputs"]["attention_mask"]
        ],
        "offer_tokens": [
            int(mask.sum()) for mask in batch["offer_inputs"]["attention_mask"]
        ],
    })
print("\ntrain batch sample:")
display(preview_batch(train_batch))
if "batch_stats" in train_batch:
    pprint(train_batch["batch_stats"])
print("\nval batch sample:")
display(preview_batch(val_batch))
if "batch_stats" in val_batch:
    pprint(val_batch["batch_stats"])

Output()

Loaded dataset: {'train_rows': 9510, 'val_rows': 490, 'train_queries': 6626, 'val_queries': 348, 'train_offers': 9441, 'val_offers': 487, 'train_positive_rows': 7588, 'val_positive_rows': 396, 'train_negative_rows': 1922, 'val_negative_rows': 94, 'val_query_share': 0.049899627186693434, 'val_offer_share': 0.04905318291700242, 'val_row_share': 0.049, 'train_positive_rate': 0.7978969505783385, 'val_positive_rate': 0.8081632653061225, 'shared_offers_between_train_and_val': 0, 'skipped_rows': 0, 'eligible_train_queries': 1541, 'target_val_queries': 348, 'selected_val_queries': 348, 'connected_components': 6904, 'train_connected_components': 6559, 'val_connected_components': 345}
dataset stats:
{'connected_components': 6904,
 'eligible_train_queries': 1541,
 'selected_val_queries': 348,
 'shared_offers_between_train_and_val': 0,
 'skipped_rows': 0,
 'target_val_queries': 348,
 'train_connected_components': 6559,
 'train_negative_rows': 1922,
 'train_offers': 9441,
 'train_positive_rate': 0.7978969505783385,
 'train_positive_rows': 7588,
 'train_queries': 6626,
 'train_rows': 9510,
 'val_connected_components': 345,
 'val_negative_rows': 94,
 'val_offer_share': 0.04905318291700242,
 'val_offers': 487,
 'val_positive_rate': 0.8081632653061225,
 'val_positive_rows': 396,
 'val_queries': 348,
 'val_query_share': 0.049899627186693434,
 'val_row_share': 0.049,
 'val_rows': 490}

train sample (raw records):

,query_id,offer_id,query_text,offer_text,label,raw_label
0,d64715fd-4350-5320-b443-dd25700810de,Nfn8MR6+Qw6JYvHRgXFCHw==,10500300,Article Name: 10500300GL Steckglied\nEAN: 4067...,1.0,Exact
1,d64715fd-4350-5320-b443-dd25700810de,n9cPxT8VQFGdX35S/XVdpg==,10500300,Article Name: 10500300W Verschlussglied 11/E 0...,1.0,Exact
2,d7385c55-7eda-5753-a86c-9902a114fd9d,e3nnrlH+QgSFJslLOVrLEg==,6311-2Z,Article Name: Rillenkugellager mit Dichtungen ...,1.0,Exact
3,e5959a1a-579d-51a0-9804-4d312167ccbf,qAay6OS9SdKRDwRtdp178w==,Besucherkittel,"Article Name: Liscombe Besucherkittel XL, Unis...",1.0,Exact
4,e20e0c6d-6594-5df9-b114-da83376e049b,3KidsO8jSvKDGLLOc0e3MA==,Elektrisch höhenverstellbarer Schreibtisch,"Article Name: Schreibtisch Atlanta, elektrisch...",1.0,Exact

val sample (raw records):

,query_id,offer_id,query_text,offer_text,label,raw_label
0,17b60606-8cfb-5ce0-8123-d8c9d20fcefb,zFO9aIa4STC0IRWlxSENxQ==,4047322026321,"Article Name: T-Steckverbindung Blaue Serie, S...",1.0,Exact
1,47707f1c-39d2-5d8c-9a97-646676a6b14c,EUZlxHoZRNeq0uobWcdpfQ==,133186,Article Name: PHS-memory 8GB RAM Speicher für ...,1.0,Exact
2,123dd51f-447f-5f94-853a-ca54a636e316,3st32OxURG6D8+3/f5YOzg==,215-311,Article Name: Molex 3 215311 Platinenstecker-K...,1.0,Exact
3,123dd51f-447f-5f94-853a-ca54a636e316,qOcJrKIZSP6HRmVlYXDYTQ==,215-311,Article Name: Molex 4 215311 Platinenstecker-K...,1.0,Exact
4,50871cd8-7940-59a6-9039-8e255b4eee8f,PfUbH10LQf2ynbhbPslk+Q==,4250101134890,Article Name: Auffangwanne aus Polyethylen für...,1.0,Exact

train batch sample:

,query_id,offer_id,label,raw_label,query_text,offer_text,query_tokens,offer_tokens
0,10d8e175-7783-5943-bd6b-4af3ffec2ec3,cB0ImfMTSE6OpVuQO8UOEA==,1.0,Exact,216931,Article Name: 10061868 WISKA Verschraubung nie...,2,256
1,227dfa8d-20e1-5f3d-87cc-5e41676c40b3,iSohnsDFTju7wUK0sKHrCA==,1.0,Exact,Bleistifte output,"Article Name: Eco-Bleistifte HB 6er Pack, rund...",4,89
2,2f545fae-205f-528f-ad50-f0d94c3505be,kOztWZiTQ9aTTDXu2nF6Pg==,1.0,Exact,drehmoment,Article Name: Wera Serie 7400 Kraftform ESD Dr...,3,256
3,e542d18a-511a-51ea-8cb2-f91c0f7d3978,hGR7P1HVRqudWyT0VA43UA==,1.0,Exact,Unterlegblech,Article Name: Bito Unterlegblech SRN-L 53x 38....,3,84
4,15602c66-c446-52e6-bc65-dda8fbdd54ec,uqaYGUP9Rv+VPZXcRPDpEg==,1.0,Exact,cd-r,"Article Name: CD-R 700 MB, 52x, Thermisch bedr...",4,256
5,e9c73f92-ba68-5dce-a34d-689159f5cdda,qH8QXhrCSdyFCBaC3E7jBg==,1.0,Exact,CLASSIC 110 Steuerleitung,"Article Name: Steuerleitung CLASSIC 110, 3 x 2...",5,256
6,8d30dc1c-3f25-5747-abc6-b86299026c22,4zTVGIP/TPiYyyZCtdksXQ==,1.0,Exact,Mülleimer,"Article Name: Mülleimer 2-fach, 2x30l EAN: 000...",4,114
7,233f32f0-0c8f-5a73-9750-13ab4bddac92,npXu4g7fRsGPzpWRsUSySQ==,1.0,Exact,Arbeitsplatte,Article Name: Arbeitsplatte ARBPL-F.WRKBANK-MA...,2,123
8,343af191-3048-53de-aa93-6276f55774f2,VRgTcJi4R3+QfXzNAFlkLg==,1.0,Exact,dosenlibelle,Article Name: Dosenlibelle 50mm 10 min BMI EAN...,4,132
9,18253565-a2b3-53af-8cbf-f4d332685f29,HteJOtXGT4+8rarsKDsu4g==,1.0,Exact,schutzhandschuhe leder,"Article Name: Handschuhe Adler-C Gr.10,5 natur...",5,183
10,353baad2-410c-57a7-984b-3b7e86f2ec58,qo4HoSg8Raytp/dIerpjAw==,1.0,Exact,planer,"Article Name: Brunnen Buchkalender 1078166906,...",1,154
11,28e39243-4d2a-50ce-a14c-e896a46d28b0,jbbS2IWMQzCmidxrvnJgIw==,1.0,Exact,salix 38,Article Name: ESD Sicherheitshalbschuh S1 EAN:...,3,179
12,4fedb271-d64e-5811-96f7-e042775766da,TrT+YfxeR9qpCo668p8yeQ==,1.0,Exact,0R 0805,Article Name: MULTICOMP PRO MP000003 WIDERSTAN...,4,184
13,8b2a72e8-1f5e-5721-8446-547b8248619d,6cq1d79pSNuZOyU6HZH2NA==,0.0,Complement,122250 7,"Article Name: VHM-Spiralbohrer, unbeschichtet,...",3,245
14,4bdef8d2-84cb-5445-bd99-62323a4c8979,uIW3afFbRH6vw43R5elK9Q==,1.0,Exact,schneider,"Article Name: Fineliner, 0,1 mm, schwarz EAN: ...",2,237
15,12c14942-0538-5d3c-a798-4e4b8061a199,o36SsPYnT9mEafEXu4n3Nw==,1.0,Exact,wagen,"Article Name: Servierwagen, 2 Etagen, 2 Schieb...",2,238

val batch sample:

,query_id,offer_id,label,raw_label,query_text,offer_text,query_tokens,offer_tokens
0,17b60606-8cfb-5ce0-8123-d8c9d20fcefb,zFO9aIa4STC0IRWlxSENxQ==,1.0,Exact,4047322026321,"Article Name: T-Steckverbindung Blaue Serie, S...",4,210
1,47707f1c-39d2-5d8c-9a97-646676a6b14c,EUZlxHoZRNeq0uobWcdpfQ==,1.0,Exact,133186,Article Name: PHS-memory 8GB RAM Speicher für ...,2,138
2,123dd51f-447f-5f94-853a-ca54a636e316,3st32OxURG6D8+3/f5YOzg==,1.0,Exact,215-311,Article Name: Molex 3 215311 Platinenstecker-K...,3,200
3,123dd51f-447f-5f94-853a-ca54a636e316,qOcJrKIZSP6HRmVlYXDYTQ==,1.0,Exact,215-311,Article Name: Molex 4 215311 Platinenstecker-K...,3,155
4,50871cd8-7940-59a6-9039-8e255b4eee8f,PfUbH10LQf2ynbhbPslk+Q==,1.0,Exact,4250101134890,Article Name: Auffangwanne aus Polyethylen für...,4,230
5,dcfbb042-a158-5607-ad0b-35c53b98c02d,4c2C2gEjThWS2AvxEKLGlw==,1.0,Exact,5015650,Article Name: OBO BETTERMANN Potenzialausgleic...,2,150
6,11db3e6a-9c98-5af5-bd4b-0127162b6556,MjCd/DKvR3G3FbeN6LMbZg==,0.0,Irrelevant,5380 1/2,"Article Name: Sunon DC-Axiallüfter, 12 V dc / ...",3,153
7,11db3e6a-9c98-5af5-bd4b-0127162b6556,int4U9I2RUGkdcaaiuo+sw==,0.0,Substitute,5380 1/2,Article Name: Huco 1 glatt Universalgelenk Sta...,3,170
8,11db3e6a-9c98-5af5-bd4b-0127162b6556,vfJEKtATQvarBxQR4/mKDw==,0.0,Substitute,5380 1/2,"Article Name: Widerstand, Dickschicht, SMD 181...",3,199
9,11db3e6a-9c98-5af5-bd4b-0127162b6556,Nz69QDfbQkiBtdJzulHqRw==,0.0,Irrelevant,5380 1/2,Article Name: PVC Steuerleitung JZ-603-CY 12 x...,3,254
10,e419feb4-dba0-598b-a340-e0ab228cef2f,557KkR/ATKuO8R0JsKRMNg==,0.0,Irrelevant,58320200,Article Name: Bolzenschneider M00 mit Wechsel-...,3,171
11,e419feb4-dba0-598b-a340-e0ab228cef2f,HyrgD6AcRZuG7PpbPu4oPw==,0.0,Substitute,58320200,Article Name: 5813720200 (V581-5/3PC-024AC-I3-...,3,145
12,2e8e379b-dc93-5d44-b2d4-42b775de25ec,O/sT+uLLQymuBUgOY7DavQ==,1.0,Exact,777314,Article Name: Not-Aus-Schaltgerät PNOZX3.10P 7...,2,188
13,29a90a97-9fcd-56f9-bfca-40baa025d096,dhu6eecNTn24TkGUiT0BHw==,1.0,Exact,Atlas Runner 65,Article Name: ATLAS Halbschuh RUNNER 65 - S1P ...,4,256
14,29a90a97-9fcd-56f9-bfca-40baa025d096,5D6B6VJ3SbetNTXRpyf7AQ==,1.0,Exact,Atlas Runner 65,Article Name: ATLAS Halbschuh RUNNER 65 - S1P ...,4,256
15,0ec1dc41-d4f6-5565-ade2-dd110680ad2f,y6QDwQf7TGaRQQWkoUAkSw==,1.0,Exact,DIN 914,Article Name: DIN 914 A 4 M 4 x 4 A 4 S EAN: 4...,3,112